version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  aws-s3: circleci/aws-s3@3.0

executors:
  node:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.14.0
  cypress:
    working_directory: ~/repo
    docker:
      - image: cypress/base:16.14.0

workflows:
  check_pull_request:
    jobs:
      - checkout:
          filters:
            branches:
              ignore:
                - develop
                - production
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout

      - build:
          requires:
            - checkout

  deploy_develop:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - develop
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout

      - build:
          requires:
            - checkout

      - run_cypress:
          requires:
            - build
          env: develop

      - push_to_s3:
          to: develop
          requires:
            - lint
            - test
            - build
            - run_cypress

  deploy_production:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - production
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout

      - build:
          requires:
            - checkout

      - run_cypress:
          requires:
            - build
          env: production

      - push_to_s3:
          to: production
          requires:
            - lint
            - test
            - build
            - run_cypress

jobs:
  checkout:
    executor: node
    steps:
    - checkout
    - persist_to_workspace:
        root: ~/repo
        paths:
          - .

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - restorecache
      - yarn_install
      - savecache
      - run: yarn lint

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - restorecache
      - yarn_install
      - savecache
      - run: yarn test:ci

  build:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - restorecache
      - yarn_install
      - savecache
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build

  run_cypress:
    parameters:
      env:
        type: string
    executor: cypress
    steps:
      - attach_workspace:
          at: ~/repo
      - restorecache
      - yarn_install
      - savecache
      - run: yarn run cy:ci:<< parameters.env >>

  push_to_s3:
    executor: aws-cli/default
    parameters:
      to:
        type: string
      from:
        type: string
        default: build
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-s3/sync:
          from: << parameters.from >>
          to: s3://aws-circleci-demo/<< parameters.to >>

commands:
  restorecache:
    description: Load yarn packages from cache
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-

  savecache:
    description: Save yarn packages to cache
    steps:
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache

  yarn_install:
    description: Install yarn packages
    steps:
      - run: yarn install --frozen-lockfile

