version: 2.1

executors:
  node:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.0.0

workflows:
  test:
    jobs:
      - checkout

      - test:
          requires:
            - checkout

      - lint:
          requires:
            - checkout

jobs:
  checkout:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  lint:
    executor: node
    steps:
      - run: yarn lint

  test:
    executor: node
    steps:
      - run: yarn test



